{{- if .Values.web.ingress.enabled -}}
apiVersion:  {{ include "temporal.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "temporal.componentname" (list . "web") }}
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Chart.Name }}
{{- with .Values.web.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- range .Values.web.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
      {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
      {{- $url := splitList "/" . }}
      - host: {{ first $url }}
        http:
          paths:
            - path: /{{ rest $url | join "/" }}
            {{ if eq (include "temporal.ingress.apiVersion" $) "networking.k8s.io/v1" }}
              pathType: Prefix
              backend:
                service:
                  name: {{ include "temporal.fullname" $ }}-web
                  port:
                    number: {{ $.Values.web.service.port }}            
            {{ else }}
              backend:
                serviceName: {{ include "temporal.fullname" $ }}-web
                servicePort: {{ $.Values.web.service.port }}
            {{- end}}
        {{- end}}
        {{- end }}
